=== nasyrovt/CabinetMedicalProject/xsd/patient.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema targetNamespace="http://www.ujf-grenoble.fr/l3miage/patient"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns:pat="http://www.ujf-grenoble.fr/l3miage/patient"
           elementFormDefault="qualified">
    <!--- ENG: Simple scheme to validate and use a new Namespace xmlns:act
          FR:Une schema simple definissant un espace de nom xmlns:act -->
    <xs:element name="patient" type="pat:Patient"/>
    <xs:complexType name="Patient">
        <xs:sequence>
            <xs:element type="xs:string" name="nom"/>
            <xs:element type="xs:string" name="prenom"/>
            <xs:element type="xs:string" name="sexe"/>
            <xs:element type="xs:date" name="naissance"/>
            <xs:element type="xs:long" name="numeroSS"/>
            <xs:element type="pat:Adresse" name = "adresse"/>
            <xs:element type="pat:Visite" name ="visite" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="Adresse">
        <xs:sequence>
            <xs:element name="numero" type="xs:byte" minOccurs="0" maxOccurs="1"/>
            <xs:element name="rue" type="xs:string"/>
            <xs:element name="codePostal" type="xs:int" />
            <xs:element name="ville" type="xs:string" />
            <xs:choice>
                <xs:element name="etage" type="xs:byte"  minOccurs="0" maxOccurs="1"/>
            </xs:choice>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="Visite">
        <xs:sequence>
            <xs:element name="intervenant" type="pat:Intervenant"/>
            <xs:element name="acte" type="xs:string"/>
        </xs:sequence>
        <xs:attribute type="xs:date" name="date" use="required"/>
    </xs:complexType>
    <xs:complexType name="Intervenant">
        <xs:sequence>
            <xs:element type="xs:string" name="nom"/>
            <xs:element type="xs:string" name="prenom"/>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== nasyrovt/CabinetMedicalProject/xml/patient.xml
<?xml version="1.0" encoding="UTF-8"?>
<patient xmlns:act="http://www.ujf-grenoble.fr/l3miage/actes" xmlns:cab="http://test/cabinet"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://www.ujf-grenoble.fr/l3miage/patient"
         xsi:schemaLocation="http://www.ujf-grenoble.fr/l3miage/patient ../xsd/patient.xsd">
    <nom>Pien</nom>
    <prenom>Oscare</prenom>
    <sexe>M</sexe>
    <naissance>1975-03-25</naissance>
    <numeroSS>65</numeroSS>
    <adresse>
        <rue>rue Casimir Brenier</rue>
        <codePostal>38000</codePostal>
        <ville>Grenoble</ville>
    </adresse>
    <visite date="2015-12-11">
        <intervenant>
            <nom>Sticke</nom>
            <prenom>Sophie</prenom>
        </intervenant>
        <acte>
            Saignée.
        </acte>
        <acte>
            Inection intraveineuse directe isolée.
        </acte>
    </visite>
    <visite date="2015-12-12">
        <intervenant>
            <nom>Frechie</nom>
            <prenom>Sarah</prenom>
        </intervenant>
        <acte>
            Prélèvement par ponction veineuse directe.
        </acte>
        <acte>
            Prélèvement aseptique cutané ou de sécrétions muqueuses, prélèvement
            de selles ou d'urine pour examens sytologiques, bactériologiques, mycologiques.
        </acte>
    </visite>
</patient>
